name: Web Scraping

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the script
      run: python test.py

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: scraped-links
        path: scraped_links.txt
