name: Scrape and Save Links

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run Python script
        run: python test.py

      - name: Print GH_TOKEN
        run: echo "Token: ${{ secrets.GH_TOKEN }}"

      - name: Set Git remote URL
        run: git remote set-url origin https://$GH_TOKEN@github.com/${{ github.repository }}.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: git add . && git commit -m "Add scraped links" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
