name: Scrape and Save Links

on:
  push:
    branches:
      - main

jobs:
  scrape_links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Run the script
      run: python test.py

    - name: Commit and push changes
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add trying\\scraped_links.txt
        git commit -m "Add scraped links"
        git push
